[tool.ruff]
target-version = 'py310'
line-length = 100
indent-width = 4
fix = true
ignore-init-module-imports = true

[tool.ruff.lint]
extend-select = ['I']
extend-fixable = ['I']
ignore = [
    'D203', # one-blank-line-before-class
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = 'double'
inline-quotes = 'single'

[tool.ruff.format]
quote-style = 'double'
indent-style = 'space'
skip-magic-trailing-comma = false
line-ending = 'lf'

[tool.ruff.lint.isort]
section-order = [
    'future',
    'standard-library',
    'third-party',
    'first-party',
    'local-folder',
    'known_tests',
]

[tool.ruff.lint.isort.sections]
# Group all test imports
'known_tests' = ['test', 'tests']
